name: Build Android Release

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    name: Build AAB
    runs-on: ubuntu-latest

    steps:
      # clone repository files
      - name: Checkout code
        uses: actions/checkout@v4

      # write gradle signing properties before gradle runs
      - name: Write Gradle signing properties
        run: |
          set -euo pipefail
          mkdir -p "$HOME/.gradle" "$HOME/keystore"
          {
            echo "RELEASE_STORE_FILE=$HOME/keystore/upload-key.jks"
            echo "RELEASE_STORE_PASSWORD=${{ secrets.RELEASE_STORE_PASSWORD }}"
            echo "RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}"
            echo "RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}"
          } > "$HOME/.gradle/gradle.properties"

      # install java 17 (temurin) for gradle builds
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # install android sdk and required tools
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # remove broken gradle wrapper jar if it exists
      - name: Clean any leftover/broken wrapper
        run: rm -f gradle/wrapper/gradle-wrapper.jar

      # download gradle 8.7 for consistent builds
      - name: Download Gradle 8.7
        run: |
          set -euo pipefail
          curl -sL https://services.gradle.org/distributions/gradle-8.7-bin.zip -o gradle.zip
          unzip -q gradle.zip
          echo "$PWD/gradle-8.7/bin" >> "$GITHUB_PATH"

      # generate gradle wrapper for version 8.7
      - name: Generate Gradle Wrapper (8.7)
        run: gradle wrapper --gradle-version 8.7

      # make gradlew executable for ci
      - name: Make Gradle executable
        run: chmod +x gradlew

      # decode and restore keystore from github secret
      - name: Restore keystore from secret
        run: |
          set -euo pipefail
          echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 --decode > "$HOME/keystore/upload-key.jks"

      # build signed release bundle with detailed logging
      - name: Build signed Release bundle
        run: ./gradlew --no-daemon --stacktrace --info clean bundleRelease

      # verify aab signature integrity
      - name: Verify AAB signature
        run: jarsigner -verify app/build/outputs/bundle/release/app-release.aab

      # upload final aab artifact to github actions
      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/bundle/release/app-release.aab
