name: Build Android Release

on:
  workflow_dispatch: {}

jobs:
  build:
    name: Build AAB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Clean any leftover/broken wrapper
        run: rm -f gradle/wrapper/gradle-wrapper.jar

      - name: Download Gradle 8.2.1
        run: |
          curl -sL https://services.gradle.org/distributions/gradle-8.2.1-bin.zip -o gradle.zip
          unzip -q gradle.zip
          echo "$PWD/gradle-8.2.1/bin" >> $GITHUB_PATH

      - name: Generate Gradle Wrapper (8.2.1)
        run: gradle wrapper --gradle-version 8.2.1

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Restore keystore from secret
        run: echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 --decode > upload-key.jks
        shell: bash

      - name: Write Gradle signing properties
        run: |
          mkdir -p ~/.gradle
          cat > ~/.gradle/gradle.properties <<EOF
RELEASE_STORE_FILE=$GITHUB_WORKSPACE/upload-key.jks
RELEASE_STORE_PASSWORD=${{ secrets.RELEASE_STORE_PASSWORD }}
RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}
RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}
EOF

      - name: Build signed Release bundle
        run: ./gradlew --no-daemon clean bundleRelease

      - name: Verify AAB signature
        run: jarsigner -verify app/build/outputs/bundle/release/app-release.aab
        shell: bash

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/bundle/release/app-release.aab
